version: "3"

services:
  clef-1:
    image: ethersphere/clef:0.4.7
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    volumes:
      - $PWD/clef1:/app/data
    command: full
  bee-1:
    image: ethersphere/bee:0.5.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:1133
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-1:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR=:1135
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR=:1134
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1133}${BEE_API_ADDR:-:1133}"
      - "${P2P_ADDR:-1134}${BEE_P2P_ADDR:-:1134}"
      - "${DEBUG_API_ADDR:-1135}${BEE_DEBUG_API_ADDR:-:1135}"
    volumes:
      - $PWD/bee1:/home/bee/.bee
    command: start
    depends_on:
      - clef-1

  clef-2:
    image: ethersphere/clef:0.4.7
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    volumes:
      - $PWD/clef2:/app/data
    command: full
  bee-2:
    image: ethersphere/bee:0.5.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:1233
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-2:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR=:1235
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR=:1234
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1233}${BEE_API_ADDR:-:1233}"
      - "${P2P_ADDR:-1234}${BEE_P2P_ADDR:-:1234}"
      - "${DEBUG_API_ADDR:-1235}${BEE_DEBUG_API_ADDR:-:1235}"
    volumes:
      - $PWD/bee2:/home/bee/.bee
    command: start
    depends_on:
      - clef-2

  clef-3:
    image: ethersphere/clef:0.4.7
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    volumes:
      - $PWD/clef3:/app/data
    command: full
  bee-3:
    image: ethersphere/bee:0.5.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:1333
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-3:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR=:1335
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR=:1334
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1333}${BEE_API_ADDR:-:1333}"
      - "${P2P_ADDR:-1334}${BEE_P2P_ADDR:-:1334}"
      - "${DEBUG_API_ADDR:-1135}${BEE_DEBUG_API_ADDR:-:1335}"
    volumes:
      - $PWD/bee3:/home/bee/.bee
    command: start
    depends_on:
      - clef-3

  clef-4:
    image: ethersphere/clef:0.4.7
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    volumes:
      - $PWD/clef4:/app/data
    command: full
  bee-4:
    image: ethersphere/bee:0.5.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:1433
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-4:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR=:1435
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR=:1434
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1433}${BEE_API_ADDR:-:1433}"
      - "${P2P_ADDR:-1434}${BEE_P2P_ADDR:-:1434}"
      - "${DEBUG_API_ADDR:-1435}${BEE_DEBUG_API_ADDR:-:1435}"
    volumes:
      - $PWD/bee4:/home/bee/.bee
    command: start
    depends_on:
      - clef-4

  clef-5:
    image: ethersphere/clef:0.4.7
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    volumes:
      - $PWD/clef5:/app/data
    command: full
  bee-5:
    image: ethersphere/bee:0.5.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:1533
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-5:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR=:1535
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR=:1534
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1533}${BEE_API_ADDR:-:1533}"
      - "${P2P_ADDR:-1534}${BEE_P2P_ADDR:-:1534}"
      - "${DEBUG_API_ADDR:-1535}${BEE_DEBUG_API_ADDR:-:1535}"
    volumes:
      - $PWD/bee5:/home/bee/.bee
    command: start
    depends_on:
      - clef-5

  clef-6:
    image: ethersphere/clef:0.4.7
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    volumes:
      - $PWD/clef6:/app/data
    command: full
  bee-6:
    image: ethersphere/bee:0.5.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:16633
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-6:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR=:16635
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR=:16634
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-16633}${BEE_API_ADDR:-:16633}"
      - "${P2P_ADDR:-16634}${BEE_P2P_ADDR:-:16634}"
      - "${DEBUG_API_ADDR:-16635}${BEE_DEBUG_API_ADDR:-:16635}"
    volumes:
      - $PWD/bee6:/home/bee/.bee
    command: start
    depends_on:
      - clef-6

  clef-7:
    image: ethersphere/clef:0.4.7
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    volumes:
      - $PWD/clef7:/app/data
    command: full
  bee-7:
    image: ethersphere/bee:0.5.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:1733
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-7:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR=:1735
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR=:1734
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1733}${BEE_API_ADDR:-:1733}"
      - "${P2P_ADDR:-1734}${BEE_P2P_ADDR:-:1734}"
      - "${DEBUG_API_ADDR:-1735}${BEE_DEBUG_API_ADDR:-:1735}"
    volumes:
      - $PWD/bee7:/home/bee/.bee
    command: start
    depends_on:
      - clef-7

  clef-8:
    image: ethersphere/clef:0.4.7
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    volumes:
      - $PWD/clef8:/app/data
    command: full
  bee-8:
    image: ethersphere/bee:0.5.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:1833
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-8:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR=:1835
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR=:1834
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1833}${BEE_API_ADDR:-:1833}"
      - "${P2P_ADDR:-1834}${BEE_P2P_ADDR:-:1834}"
      - "${DEBUG_API_ADDR:-1835}${BEE_DEBUG_API_ADDR:-:1835}"
    volumes:
      - $PWD/bee8:/home/bee/.bee
    command: start
    depends_on:
      - clef-8

  clef-9:
    image: ethersphere/clef:0.4.7
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    volumes:
      - $PWD/clef9:/app/data
    command: full
  bee-9:
    image: ethersphere/bee:0.5.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:1933
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-9:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR=:1935
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR=:1934
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1933}${BEE_API_ADDR:-:1933}"
      - "${P2P_ADDR:-1934}${BEE_P2P_ADDR:-:1934}"
      - "${DEBUG_API_ADDR:-1935}${BEE_DEBUG_API_ADDR:-:1935}"
    volumes:
      - $PWD/bee9:/home/bee/.bee
    command: start
    depends_on:
      - clef-9

  clef-10:
    image: ethersphere/clef:0.4.7
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    volumes:
      - $PWD/clef10:/app/data
    command: full
  bee-10:
    image: ethersphere/bee:0.5.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:11033
      - BEE_BOOTNODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-10:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_DB_CAPACITY
      - BEE_DEBUG_API_ADDR=:11035
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR=:11034
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-11033}${BEE_API_ADDR:-:11033}"
      - "${P2P_ADDR:-11034}${BEE_P2P_ADDR:-:11034}"
      - "${DEBUG_API_ADDR:-11035}${BEE_DEBUG_API_ADDR:-:11035}"
    volumes:
      - $PWD/bee10:/home/bee/.bee
    command: start
    depends_on:
      - clef-10
volumes:
  clef-1:
  bee-1:
  clef-2:
  bee-2:
  clef-3:
  bee-3:
  clef-4:
  bee-4:
  clef-5:
  bee-5:
  clef-6:
  bee-6:
  clef-7:
  bee-7:
  clef-8:
  bee-8:
  clef-9:
  bee-9:
  clef-10:
  bee-10: